// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_jod-qGkkOAL9-P_HadANW_e_vcfJlqY',
    appId: '1:588740103888:web:418fb0bc222d965ef598d5',
    messagingSenderId: '588740103888',
    projectId: 'crud-d40f5',
    authDomain: 'crud-d40f5.firebaseapp.com',
    storageBucket: 'crud-d40f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkF-4kGfLfupM9hGsf_Ti6cC-96Y0t_MY',
    appId: '1:588740103888:android:5b7a3c2093055ef4f598d5',
    messagingSenderId: '588740103888',
    projectId: 'crud-d40f5',
    storageBucket: 'crud-d40f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkW0KKCnjs_SNGZU1Zyt7oOSQfVWgJDk',
    appId: '1:588740103888:ios:df4adc52a3d08997f598d5',
    messagingSenderId: '588740103888',
    projectId: 'crud-d40f5',
    storageBucket: 'crud-d40f5.appspot.com',
    iosBundleId: 'com.example.fireUi',
  );
}
